<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-0A8DN9C" failures="0" tests="1" name="TestNG.ex5_TestNGKeywords4_Timeout" time="5.252" errors="1" timestamp="2024-11-11T21:08:48 IST" skipped="0">
  <testcase classname="TestNG.ex5_TestNGKeywords4_Timeout" name="TC3" time="5.252">
    <error message="Method TestNG.ex5_TestNGKeywords4_Timeout.TC3() didn&#039;t finish within the time-out 5000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNG.ex5_TestNGKeywords4_Timeout.TC3() didn't finish within the time-out 5000
at java.base@17.0.10/java.lang.Thread.sleep(Native Method)
at app//TestNG.ex5_TestNGKeywords4_Timeout.TC3(ex5_TestNGKeywords4_Timeout.java:10)
at java.base@17.0.10/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.10/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.10/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.10/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.10/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.10/java.lang.Thread.run(Thread.java:842)
]]>
    </error>
  </testcase> <!-- TC3 -->
</testsuite> <!-- TestNG.ex5_TestNGKeywords4_Timeout -->
